name: login_signup
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dotted_border: ^2.0.0
  english_words: ^4.0.0
  firebase_core: ^3.13.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  geolocator: ^14.0.1
  go_router: ^15.1.1
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  provider: ^6.1.4
  shared_preferences: ^2.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
